### ISSUE TITLE
Importing .craft files

### ISSUE THREAD

**Issue by krispq** [ShoosGun/Kerbal-Space-Ventures#1]
Does this mod allow you to import any .craft file into Outer Wilds? I've tried dropping other .craft files (other than Alpha and Beta) in the mod folder but they are not spawning in-game (although they are being properly read).
So I was wondering if that's possible or it's just limited to a few parts.

**Comment by loco-choco** [comment]
For now it is limited to very few parts, mostly only the ones on the beta.craft.
